import type { CheckSeverity } from '@cronos/core';

export type ReportLanguage = 'es' | 'en';

const es = {
  docTitle: (blast: string) => `Informe de voladura · ${blast}`,
  title: 'Informe de voladura',
  summary: 'Resumen',
  holes: 'Taladros',
  holesValue: (total: number, loaded: number) => `${total} (${loaded} cargados)`,
  drilled: 'Metros perforados',
  diameter: 'Diámetro',
  benchHeight: 'Altura de banco',
  explosive: 'Explosivo',
  primers: 'Primas',
  volume: 'Volumen cubicado',
  tonnage: 'Tonelaje cubicado',
  loadingFactor: 'Factor de carga real',
  designFactor: 'Factor de carga de diseño (B·S·H)',
  energy: 'Energía',
  cost: 'Costo de productos',
  duration: 'Duración de la secuencia',
  noTimes: 'sin tiempos',
  maxPerDelay: (windowMs: string) => `Máx. kg por retardo (${windowMs} ms)`,
  coincident: 'Grupos coincidentes',
  flyrock: 'Alcance flyrock (Lundborg)',
  plan: 'Plano',
  planByTime: 'Plano (color: tiempo de disparo)',
  north: 'N',
  chargeByProduct: 'Carguío por producto',
  noCharge: '(sin carga)',
  fragTitle: 'Fragmentación (Kuz-Ram + Swebrec)',
  noLoadedHoles: 'Sin taladros cargados.',
  rockFactor: 'Factor de roca A',
  uniformity: 'Índice de uniformidad n',
  oversize: 'Sobretamaño (> 100 cm)',
  vibTitle: 'Vibración y sobrepresión',
  ppvLaw: 'Ley de PPV',
  mic: 'Carga máx. por retardo',
  micExtended: 'Con ventana ampliada (pirotécnicos, P-10)',
  electronicOnly: '- (solo electrónicos)',
  monitoringPoint: 'Punto de control',
  limit: 'Límite',
  admissible: 'kg adm.',
  exceeds: ' (EXCEDE)',
  noMonitoringPoints: '(sin puntos de control)',
  interRow: 'Retardo entre filas',
  rows: 'Filas',
  minMs: 'mín [ms]',
  maxMs: 'máx [ms]',
  meanMs: 'media [ms]',
  review: 'Revisión del diseño',
  noObservations: 'Sin observaciones.',
  observation: 'Observación',
  level: 'Nivel',
  severity: { error: 'error', warning: 'advertencia', info: 'nota' } satisfies Record<
    CheckSeverity,
    string
  >,
  assumptions: 'Modelos, parámetros y supuestos',
  continued: '(cont.)',
  allStructures: 'todas',
  holeTable: [
    'Taladro',
    'Este',
    'Norte',
    'Cota',
    'Largo',
    'Ø mm',
    'Incl °',
    'Az °',
    'kg',
    't [ms]',
  ],
  holeRange: (from: number, to: number, total: number) => `Taladros (${from}–${to} de ${total})`,
  notes: {
    units:
      'Unidades SI internas; los resultados se recalculan desde el diseño y no se guardan como fuente de verdad.',
    deckCharge:
      'Carga por tramo con π/4 exacto: DCL = (π/4)·Ø²·ρ; masa = DCL·(largo − esponjamiento) (docs/theory/02 §2).',
    volume: (lopezJimeno: boolean) =>
      `Volumen de diseño B·S·H con H vertical (P-06); volumen real por áreas de influencia recortadas al perímetro. Sobreperforación: ${lopezJimeno ? 'López Jimeno, L = H/cos α + (1 − α/100)·J' : 'vertical bajo el piso, L = (H + J)/cos α'} (P-05).`,
    timing: (windowMs: string) =>
      `Tiempos: Dijkstra sobre el amarre + retardo de fondo. Carga máxima por retardo con ventana semiabierta [t, t + ${windowMs} ms) (P-10).`,
    burden: (reliefMs: string) =>
      `Burden efectivo: distancia a la superficie libre más cercana al detonar; un taladro previo alivia si salió al menos ${reliefMs} ms por metro de burden antes y está delante (P-02, P-16).`,
    sdob: (severe: string, safe: string) =>
      `Profundidad escalada de enterramiento (Chiappetta): carga superior, primeros 10·Ø, D solo con material confinante (P-01, P-14); avisos < ${severe} (severa) y < ${safe} m/kg^(1/3), rangos de fuente secundaria.`,
    ppv: (law: string) =>
      `PPV = K·(R/√Q)^(−β) en campo lejano con la distancia al taladro más cercano de la ventana (P-07); K y β del sitio${law} o del punto; son constantes de sitio, no universales.`,
    limits: (list: string) => `Límites de PPV: ${list || 'sin tabla'}.`,
    airblast:
      'Sobrepresión P = k·(R/W^(1/3))^(−β) y alcance de proyecciones de Lundborg: modelos empíricos, informativos.',
    frag: 'Fragmentación: Kuz-Ram (Cunningham 1987, n) con RWS y Swebrec; regresión hasta validar con un ejemplo publicado (P-08).',
    generic: (count: number, names: string) =>
      `Atención: ${count} explosivo(s) con valores genéricos sin ficha técnica (${names}); reemplazar por la ficha del fabricante.`,
    allCited: 'Todos los explosivos citan su ficha técnica.',
    rules:
      'Las reglas por debajo del estado R3 (docs/RULES.md) solo avisan; no bloquean el diseño.',
  },
  /** Títulos de observaciones por `check.id`; el núcleo ya los da en español. */
  checks: {} as Record<string, string>,
};

const en = {
  docTitle: (blast: string) => `Blast report · ${blast}`,
  title: 'Blast report',
  summary: 'Summary',
  holes: 'Holes',
  holesValue: (total: number, loaded: number) => `${total} (${loaded} loaded)`,
  drilled: 'Drilled metres',
  diameter: 'Diameter',
  benchHeight: 'Bench height',
  explosive: 'Explosive',
  primers: 'Primers/boosters',
  volume: 'Volume',
  tonnage: 'Tonnage',
  loadingFactor: 'Loading factor (actual)',
  designFactor: 'Design factor (B·S·H)',
  energy: 'Energy',
  cost: 'Product cost',
  duration: 'Sequence duration',
  noTimes: 'no times',
  maxPerDelay: (windowMs: string) => `Max. charge per delay (${windowMs} ms)`,
  coincident: 'Coincident groups',
  flyrock: 'Flyrock range (Lundborg)',
  plan: 'Plan view',
  planByTime: 'Plan view (colour: firing time)',
  north: 'N',
  chargeByProduct: 'Charge by product',
  noCharge: '(no charge)',
  fragTitle: 'Fragmentation (Kuz-Ram + Swebrec)',
  noLoadedHoles: 'No loaded holes.',
  rockFactor: 'Rock factor A',
  uniformity: 'Uniformity index n',
  oversize: 'Oversize (> 100 cm)',
  vibTitle: 'Vibration and airblast',
  ppvLaw: 'PPV law',
  mic: 'Max. charge per delay',
  micExtended: 'With extended window (pyrotechnic, P-10)',
  electronicOnly: '- (electronic only)',
  monitoringPoint: 'Monitoring point',
  limit: 'Limit',
  admissible: 'Adm. kg',
  exceeds: ' (EXCEEDS)',
  noMonitoringPoints: '(no monitoring points)',
  interRow: 'Inter-row delay',
  rows: 'Rows',
  minMs: 'min [ms]',
  maxMs: 'max [ms]',
  meanMs: 'mean [ms]',
  review: 'Design review',
  noObservations: 'No findings.',
  observation: 'Finding',
  level: 'Level',
  severity: { error: 'error', warning: 'warning', info: 'note' },
  assumptions: 'Models, parameters and assumptions',
  continued: '(cont.)',
  allStructures: 'all',
  holeTable: ['Hole', 'East', 'North', 'Elev.', 'Length', 'Ø mm', 'Incl °', 'Az °', 'kg', 't [ms]'],
  holeRange: (from: number, to: number, total: number) => `Holes (${from}–${to} of ${total})`,
  notes: {
    units:
      'SI units internally; results are recomputed from the design and are not stored as a source of truth.',
    deckCharge:
      'Deck charge with exact pi/4: linear charge = (pi/4)·Ø²·rho; mass = linear charge·(length - slumping) (docs/theory/02 §2).',
    volume: (lopezJimeno: boolean) =>
      `Design volume B·S·H with vertical H (P-06); actual volume from influence areas clipped to the boundary. Subdrill: ${lopezJimeno ? 'López Jimeno, L = H/cos alpha + (1 - alpha/100)·J' : 'vertical below the floor, L = (H + J)/cos alpha'} (P-05).`,
    timing: (windowMs: string) =>
      `Timing: Dijkstra over the tie-up + downhole delay. Max. charge per delay with half-open window [t, t + ${windowMs} ms) (P-10).`,
    burden: (reliefMs: string) =>
      `Effective burden: distance to the nearest free face at firing time; an earlier hole provides relief if it fired at least ${reliefMs} ms per metre of burden before and lies in front (P-02, P-16).`,
    sdob: (severe: string, safe: string) =>
      `Scaled depth of burial (Chiappetta): top charge, first 10·Ø, D only with confining material (P-01, P-14); warnings < ${severe} (severe) and < ${safe} m/kg^(1/3), ranges from a secondary source.`,
    ppv: (law: string) =>
      `PPV = K·(R/sqrt(Q))^(-beta) in the far field with the distance to the nearest hole in the window (P-07); site K and beta${law} or per point; they are site constants, not universal.`,
    limits: (list: string) => `PPV limits: ${list || 'no table'}.`,
    airblast:
      'Airblast P = k·(R/W^(1/3))^(-beta) and Lundborg flyrock range: empirical models, for information only.',
    frag: 'Fragmentation: Kuz-Ram (Cunningham 1987, n) with RWS and Swebrec; regression until validated against a published example (P-08).',
    generic: (count: number, names: string) =>
      `Warning: ${count} explosive(s) with generic values and no datasheet (${names}); replace with the manufacturer's datasheet.`,
    allCited: 'All explosives cite their datasheet.',
    rules: 'Rules below status R3 (docs/RULES.md) only warn; they do not block the design.',
  },
  checks: {
    // diagnostics/designChecks.ts
    noFreeFace: 'No free face defined',
    lowStiffness: 'Low burden stiffness',
    subdrillRange: 'Subdrill out of range',
    benchDiameter: 'Unusual diameter for the bench height',
    unloaded: 'Unloaded holes',
    overcharged: 'Column longer than the hole',
    noStemming: 'No stemming',
    shortStemming: 'Short stemming',
    longStemming: 'Long stemming',
    stemmingDiameter: 'Stemming out of range in diameters',
    noDetonator: 'Loaded without detonator',
    notInitiated: 'Loaded but not initiated',
    coincident: 'Neighbours firing together',
    duplicate: 'Duplicate collars',
    outside: 'Outside the boundaries',
    // diagnostics/chargeChecks.ts
    openColumn: 'Column does not close',
    noBooster: 'Blasting agent without booster',
    waterIncompatible: 'Explosive not suitable for water in the hole',
    belowCriticalDiameter: 'Charge diameter below critical',
    sdobSevere: 'Insufficient confinement (severe SDOB)',
    sdobLow: 'Low confinement (SDOB)',
    // timing/timingChecks.ts
    tieCycle: 'Tie-up with cycles',
    unrelievedBurden: 'Free face not relieved',
    invertedOrder: 'Firing order inverted relative to the free face',
    closeRelief: 'Relief too close',
    delayGuide: 'Delay outside the per-metre guideline',
  } as Record<string, string>,
} satisfies typeof es;

export const REPORT_TEXT: Record<ReportLanguage, typeof es> = { es, en };
